<MasterInterfaces>:
    MDBottomNavigation:
        panel_color: app.theme_cls.primary_color
        selected_color_background: 1, 0, 0, 1
        text_color_active: app.theme_cls.secondary_text_color
        use_text: False
        MDBottomNavigationItem:
            name: 'Passwords'
            PasswordsInter:
        MDBottomNavigationItem:
            name: 'Settings'
            SettingInter:
